ansible/inventories/local_development
ansible/inventories/local_testing
ansible/inventories/remote_testing
ansible/roles/common/tasks/main.yml
ansible/roles/pico-shell/tasks/main.yml
ansible/roles/pico-web/tasks/main.yml

This pull adds a common group to the ansible inventory files which allows the subsequent plays to access the common variables without explicitly calling include.

Add common group

---

ansible/roles/pico-shell/tasks/shell_manager.yml

- placed securebashrc where pam module expected it.
- this works, and matches the existing behavior of the picoCTF-platform,
but could be made much more robust

Fix pam initial login so message shows

---

ansible/roles/pico-shell/tasks/shell_manager.yml
ansible/roles/pico-web/tasks/picoCTF-webapp.yml

Before this commit, `vagrant up` will fail as of this writing due to:
```
[...]
Downloading/unpacking cryptography>=1.5 (from paramiko>=1.13.1,<3->spur->ctf-shell-manager==1.2.1)
Running setup.py (path:/tmp/pip-build-6xfnjkte/cryptography/setup.py) egg_info for package cryptography
error in cryptography setup command: Invalid environment marker: platform_python_implementation != 'PyPy'
[...]
```

Update Python setuptools before installing packages

---

picoCTF-web/api/routes/user.py
picoCTF-web/api/user.py

Use to store arbitrary data per user, such as for pioCTF game persistence.

Add user extdata routes

---

Vagrantfile

This change makes it easy to test pull requests using `git worktree` so
long as the working directory is named in the form of
`picoCTF{{suffix}}`. For example, this PR is issued from a branch in a
working directory created using `git worktree add -b
Vagrantfile-auto-name-pr ../picoCTF-Vagrantfile-auto-name-pr`. With this
change, `vagrant up` will automatically assign the machine names to have
a suffix of `-Vagrantfile-auto-name-pr`, which we may reasonably expect
to be unique on the host.

Compute vb.name automatically using directory name

---

README.md

We decided that this is a more appropriate solution than using
`.gitattibute`, as explained in #71.

Fix #68 by disabling autocrlf in the clone instruction

---

picoCTF-shell/hacksport/deploy.py
picoCTF-shell/shell_manager/problem_repo.py
picoCTF-shell/shell_manager/util.py

Similar to #73, the value of the arguments will otherwise persist to subsequent calls of the function.

Fix mutable default arguments

---

picoCTF-shell/hacksport/deploy.py
picoCTF-web/api/achievement.py
picoCTF-web/api/daemon_manager.py

Replace `logger.warn()` with `logger.warning()`.
Per https://bugs.python.org/issue14551, replace `imp.load_source()`
with `importlib.machinery.SourceFileLoader.load_module()`

Replace deprecated module and methods

---

.gitignore
Vagrantfile

- Each VM has its own console log.
- The console log is ignored, and the .gitignore has been cleaned up.
(We are not targetting terraform this year and so prepending the / is
just for safety.)
- Vagrantfile accepts overrides in CPU, GUI, MEM via env vars, e.g.,
`M=6 vagrant up shell`.

Improve debugging experience of VMs

---

ansible/roles/mongodb/defaults/main.yml
ansible/roles/mongodb/templates/mongod.conf.j2
ansible/roles/pico-web/tasks/nodejs.yml
picoCTF-web/setup.py

- Mongodb 3.2 to 3.6 (EOL TBD)
- Remove deprecated `nohttpinterface` config
- Nodejs 4.x to active LTS 8.x (EOL Dec 2019)
- Update pymongo pin to latest
Addresses #113

Update EOL MongoDB and Nodejs

---

picoCTF-web/api/config.py
picoCTF-web/api/user.py

To address issue #49: bringing back `picoCTF-web-deprecated` PR#57 username
blacklist with default ubuntu 16.04 alphanumeric user/group names, as well as
ctf names `hacksports` and `shellinabox`. Note that this measure is no longer
a matter of security against privilege escalation via ubuntu system groups
such as `sudu` (see #49 discussion), but rather to prevent the creation of
crippled web accounts that are unable to login to the shell. Does not attempt
to prevent collisions with problem instance names as ascii alphanumeric limitation
already exists for web account creation.

Reinstate web username creation blacklist

---

ansible/roles/pico-web/tasks/gunicorn.yml
ansible/roles/pico-web/templates/ctf-daemon.service.j2
ansible/roles/pico-web/templates/gunicorn.service.j2

Allows `vagrant up web` to properly start VM even after ungraceful shutdown,
re-provisioning is no longer required.
- Fix ansible task failure of enabling gunicorn service, likely due to
ambiguity of `gunicorn` to `gunicorn.service` vs `gunicorn.socket`.
- Add 15s sleep and `vboxadd-service` to `After` directive in `gunicorn` and
`ctf-daemon` service configs to ensure that they start after vbox shared
directories have had time to mount. Note that `vboxadd-service` is not
*Required*.

Fix gunicorn and ctf-daemon services starts

---

ansible/roles/pico-shell/files/pam_session.py
ansible/roles/pico-shell/tasks/pam_and_services.yml

See comments in pam_session.py for details.
In short, uses systemd to manage settings on per-user cgroups.  Changes are applied with pam at the start of a session.  Currently only applied when a pam session is opened via sshd, but will apply to all tasks (processes) in that (user's) slice.
Resources are always fair shared across all users.  All uses (except uid 0 and 1000) also have maximums applied.
Specific settings are:
* Memory:
* 512MB reserved for system (ie. not allocated to user.slice)
* 128MB max per-user (ie. per user-xxxx.slice)
* Swap (more specifically, memory+swap):
* Attempted but will quietly fail if swapaccount=1 is not enabled in kernel.
* Same settings as Memory which effectively limits swap usage in the worst case.
* CPU 
* 10% minimum available for system - (uses …

Hardening: Restrict cpu,memory,pids via cgroups

---

README.md
picoCTF-web/api/api_manager.py
picoCTF-web/api/config.py
picoCTF-web/api/email.py
picoCTF-web/api/logger.py
picoCTF-web/api/routes/admin.py
picoCTF-web/web/coffee/management-settings.coffee

Issue #21 
Email can now be configured from the web interface. Added blank fields for competition_urls and competition_name because more things are broken than just email.py; this needs to be fixed.

Fixed email

---

picoCTF-web/daemons/share_instances.py

Resolves #143. The final shell cmd was not executed by a `with` statement,
leaving lingering ssh session with every 60s run of the ctf-daemon.

Fix ctf-daemon unclosed ssh connections

---

picoCTF-web/api/problem.py

The old behavior does not accept the intended flag if DEBUG_KEY is set.
That behavior makes testing less smooth because it requires restarting
the web service to switch between accepting DEBUG_KEY for platform
testing and accepting the intended flags for problem testing. This patch
makes both types of testing possible with one VM.

Accept both intended flags and DEBUG_KEY

---

picoCTF-web/api/logger.py
picoCTF-web/api/routes/team.py
picoCTF-web/api/team.py
picoCTF-web/api/user.py
picoCTF-web/web/coffee/account.coffee

Allows anyone in team to set new team password.
Changes `/account` page to show current Join/Register team interface if no
team has been joined/created, but new Change Team Password interface if
a team has been joined/created.
Resolves #168

Add team password reset function

---

picoCTF-web/web/coffee/account.coffee
picoCTF-web/web/coffee/front-page.coffee

The team Join/Register form has a one-off bug where the default
HTML form `action` is to join, and the secondary the Register
function just calls a POST with params. The latter does not go
through form validation, so teamname or teampass could be omitted
as key, causing a nonspecific server error. This is now validated
client-side. This form is present on front-page (after reg) as well
as the account page.

Fix empty-form team registration

---

picoCTF-web/api/common.py
picoCTF-web/api/team.py
picoCTF-web/api/user.py
picoCTF-web/test/test_data/data_fabrication.py

Move hashing function from `user` module to `common`
TODO: Update all team tests
IMPORTANT: If you have existing teams created in plaintext, the
following script will hash all plaintext team passwords and is
safe to run more than once. This all applies to the `web` instance.
First, set environment variable:
`APP_SETTINGS_FILE=/picoCTF-web-config/deploy_settings.py`
Then execute this script within the `/picoCTF-env` virtualenv:
```
import api
all_teams = api.team.get_all_teams(show_ineligible=True)
for team in all_teams:
if isinstance(team["password"], str):
api.team.update_password(team["tid"], team["password"])
```

Hash team passwords

---

ansible/roles/pico-shell/templates/config.json.j2
picoCTF-shell/hacksport/deploy.py

Also make the obfuscated directory name a bit more human-friendly by
prepending the username of the problem.
There is no apparent down side to turning this option on by default and
the result is we get difficult-to-guess directory names in `/problems`:
```
root@pico-local-dev-shell:~# ls -1 /problems/
buffer-overflow-1_0_bab40cd8ebd7845e1c4c2951c6f82e1f
buffer-overflow-1_1_f49b6bd5da29513569bd87f98a934fa6
ecb-1_0_73a0108a98d2862a86f4b71534aaf7c3
ecb-1_1_83b2ed9a1806c86219347bc4982a66de
sql-injection-1_0_9e114b246c48eb158b16525f71ae2a00
sql-injection-1_1_10a4b1cdfd3a0f78d0d8b9759e6d69c5
```
(Based on my understanding, the benefit of having such obfuscated
directory names is that there is almost no chance of getting into a
wrong problem directory and thus getting the wrong flag. Of course, …

Default obfuscate_problem_directories to true; resolves #160

---

picoCTF-web/api/team.py
picoCTF-web/web/coffee/account.coffee
picoCTF-web/web/coffee/front-page.coffee

Specifically that a team cannot be created that conflicts with
an existing username. Likewise, an attempt to join a team that does
conflict with an existing username (which is in reality, a user's
starting self-team) receives the same error. The user check is
performed first when validating a team creation so that the
later team name check and "Team already exists" message does
not create confusion.

Clarify error messages when join/create teams

---

picoCTF-web/api/shell_servers.py

Resolves #164 
Before: 
Use web management interface to `Load Deployment` or `Check Status` repeatedly
From shell or web machine, `netstat | grep ssh` should show an increasing number of ESTABLISHED connections the more those two management buttons are clicked.
After:
From shell or web machine, `netstat | grep ssh` will not show increasing number of ESTABLISHED connections..

Close spur.SshShell connections when done

---

ansible/scripts/add_shell_server.py
picoCTF-web/api/config.py
picoCTF-web/api/problem.py
picoCTF-web/api/routes/admin.py
picoCTF-web/api/shell_servers.py
picoCTF-web/api/team.py
picoCTF-web/web/coffee/management-settings.coffee
picoCTF-web/web/coffee/management-shell.coffee
picoCTF-web/web/coffee/shell.coffee

Shell servers are tagged with `server_number` upon add,
and their respective problems are tagged with same.
Teams are assigned `server_numbers` based on configured
manual and auto stepping. Subsequent problem instances
assignment is limited to those problem instances on the
teamn's assigned shell server.
Teams that are assigned to not-yet added shell servers
cannot be assigned problem instances and receive an error
to contact admin.

Add shell_server sharding by problems instances

---

picoCTF-shell/hacksport/deploy.py

Based on the removal of the dry-run check when _creating_ the lock file in:
https://github.com/picoCTF/picoCTF/commit/cc43a20df700cba725893c9383081d6cf63a07ed#diff-cc177e30fab3daa3f822ac12152b15fbL601
it seems like the intent was to use the lock file for both dry-run and real deployments.
This, then, resolves #222 by removing it for dry runs as well.

Release lock file for dry-run deployments as well

---

ansible/ansible.cfg

This had been introduced in 73bb331b9af31edbdc5271196249cdd7f95b43ab
to solve an installation issue that is no longer occurring with the current versions of Ansible/spur.
Resolves #261

Remove DEFAULT_MODULE_LANG from Ansible config

---

Vagrantfile
vagrant/build_base_boxes/Vagrantfile
vagrant/local_testing/Vagrantfile

This pull-request forces Vagrant to use a network interface card (NIC) we choose, recommended by a built-in warning, as documented in #244. We chose "virtio" to mandate as NIC to the configured networks.
My testing steps were as follows:
- $ vagrant destroy
- $ vagrant up
- It should be noted here that no provisioning steps had any ominous security warnings as seen in the issue #244 
- *register user at local pico web portal*
- *submit incorrect flag*
- *submit correct flag*
All these steps worked as expected. I also manually inspected the NIC's reported by Virtualbox and found them as expected.
As raised in a related PR #257, all Vagrantfiles in the project were inspected and all mentions of network have been amended with a mandatory NIC "virtio".
Resolves #244

Configure Vagrant choice of more secure NIC's

---

picoCTF-web/api/problem.py

My tactics here for effective communication were Bottom Line Up Front. The first two words of both messages indicate success or failure. The rest of the messages is quite helpful for problem solving, but really just clarification.
@maverickwoo The messages have been standardized according to your request in the closed PR: #257 
Resolves #252

Clarified flag submission error messages (issue #252)

---

picoCTF-shell/hacksport/deploy.py
picoCTF-shell/shell_manager/package.py

Modifies the behavior of the `shell_manager deploy` command.
Previously, only the following syntax was valid:
`shell_manager deploy installed_package_name`
`shell_manager deploy -d problem_source_directory`
Now, any combination works:
```
shell_manager deploy installed-package-name|problem-source-directory
shell_manager deploy -d installed-package-name|problem-source-directory
```
When deploying a source directory (without `-d`), the .deb package is created and installed behind-the-scenes. Also of note, it is installed using `apt-get` rather than `dpkg`, so dependencies should be handled automatically, as mentioned in #111.
Wiki documentation will also need to be updated – I think recommending the use of `shell_manager deploy` directly for typical deployments, and the multi-step …

Allow direct deployment of problem directories

---

picoCTF-web/api/group.py
picoCTF-web/api/team.py
picoCTF-web/web/classroom.html
picoCTF-web/web/coffee/classroom-management.coffee
picoCTF-web/web/coffee/classroom.coffee
picoCTF-web/web/coffee/front-page.coffee
picoCTF-web/web/profile.html

Classroom progress panels and CSV columns show teamname and member name(s), allowing for multi-member teams. 
Panel title:
`team1 (alice smith, bob smith)`
CSV: 
Teamname|Member Name(s)
-|-
`team1`|alice smith, bob smith
* Resolves #209 
* Resolves #204 
* Revert eb31ad4 "Remove/hide classroom e-mail invite from UI"
* Partial revert a1aa23f "Additional adjustments to classroom per #181 issues"

Allow reg of teacher users, class shows realnames

---

picoCTF-web/api/config.py
picoCTF-web/api/problem.py
picoCTF-web/api/routes/stats.py
picoCTF-web/api/shell_servers.py
picoCTF-web/api/stats.py
picoCTF-web/api/team.py
picoCTF-web/api/user.py
picoCTF-web/daemons/cache_stats.py
picoCTF-web/daemons/share_instances.py
picoCTF-web/web/coffee/progression_graphs.coffee

- Team eligibility is computed as-needed
- Eligibility requirements are a configuration setting (long term, these could be per-event and have a richer DSL for e.g. age comparisons)
- "eligible", "ineligible", and "show_ineligible" parameters reworked into
the "include_ineligible" parameter (defaults to False)
I tested that the on-demand eligibility calculation seems to be working for 1-person teams (looking at the `/api/team` output for various accounts). I couldn't figure out how to test adding users to a different team - is that functionality broken/disabled somewhere in this repo?

Rework eligibility

---

picoCTF-shell/setup.py

To fix https://nvd.nist.gov/vuln/detail/CVE-2019-10906
Confirmed web server still comes up, seems to work fine with new version.

Resolve jinja2 vulnerability

---

picoCTF-web/api/logger.py
picoCTF-web/api/problem.py
picoCTF-web/api/routes/problem.py
picoCTF-web/api/stats.py

Previous behavior (did not actually verify submitted flag if the team had already solved the problem):
| previously submitted? | correct? | message displayed |
| --- | --- | --- |
| N | N | (error) "That is incorrect!" |
| N | Y | (success) "That is correct!" |
| Y | N | (error) "Flag correct: however, you have already received points for that flag." |
| Y | Y | (error) "Flag correct: however, you have already received points for that flag." |
New behavior:
| previously submitted? | correct? | message displayed |
| --- | --- | --- |
| N | N | (error) "That is incorrect!" |
| N | Y | (success) "That is correct!" |
| Y | N | (error) "Flag incorrect: please note that you or your team have  already solved this problem." |
| Y | Y | (success) "Flag correct: however, you have already received …

Allow regrading of solved problems

---

.isort.cfg
picoCTF-shell/shell_manager/bundle.py
picoCTF-shell/shell_manager/config.py
picoCTF-shell/shell_manager/package.py
picoCTF-shell/shell_manager/problem_repo.py
picoCTF-shell/shell_manager/run.py
picoCTF-shell/shell_manager/util.py

* Changes the `isort` [multi-line-output](https://github.com/timothycrosley/isort#multi-line-output-modes) style to *Grid* to match the formatting style of `yapf`.
* Sorts all shell-manager package imports according to `isort`.
* Removes unused imports.
* Fixes some `flake8` style issues, e.g. line too long, unused Exception variables and wrong indentation.
* Fixes some docstrings, e.g. typos, wrong indentation and changes some "imperative" docstrings to "descriptive" (according to [Google Python Style Guide](http://google.github.io/styleguide/pyguide.html))

Small shell manager code cleanups

---

.travis.yml
tox.ini

Adds an initial Travis-CI configuration (`.travis.yml`) which calls `tox` to run `flake8` and `flake8-isort`. `flake8` checks *picoCTF-web* and *picoCTF-shell* but excludes the *test* folders. The `flake8-isort` plugin invokes `isort` and will use `.isort.cfg`.
The Python version that is used for the `flake8` code analysis is 3.7.
Related issue #276

Initial CI config to run flake8 and isort

---

picoCTF-shell/shell_manager/util.py

The voluptuous "port_range_schema" in shell_manager.util allowed ports
up to 66635. But a port ranges from 0 to 65535.

Fix port range schema in shell-manager util module

---

.travis.yml
tox.ini

Adds [darglint](https://pypi.org/project/darglint/) checks to the flake8 CI job, to check that docstrings matches Google style guide. It integrates to flake8, you only have to install the package and you get the additional checks directly in flake8. To run flake8 locally, you only have to install `tox` and run:
```
tox -e flake8
```
Tox will create a virtual environment and install all dependencies for you.
Adds also the [bandit](https://pypi.org/project/bandit/) security linter as another CI job. At the moment, the default configuration is used, but we should use a custom config, later. The job is currently allowed to fail. To run bandit locally, you only have to install `tox` and run:
```
tox -e bandit
```
Related issue #276

Add darglint and bandit linter to CI config

---

ansible/roles/pico-shell/tasks/main.yml

In the past, the program "wall" would enable any competitor to broadcast a message to the terminals of all other shell server users. There are other such programs for "inter-user" communication on an Ubuntu box, but "wall" is esp. powerful. The solution I decided on, proposed by @maverickwoo in #205 , was to disable the reception of other users' messages by default by appending "mesg n" to the end of "/etc/profile". This protects shell server users from possible spam.
Testing this change:
From a fresh "vagrant up" I verified that the "mesg n" line was at the end of "/etc/profile". I verified that after my change, a normal user did not receive messages from other users.
Resolves #280

Added ansible task to disable inter-user communication by default

---

.travis.yml
README.md
picoCTF-shell/requirements.txt
picoCTF-shell/tests/test_problems.py
picoCTF-shell/tests/unit/test_config.py
picoCTF-shell/tests/unit/test_util.py
tox.ini

Adds a *tox* environment to run *picoCTF-shell* tests with code coverage. The old shell tests are set to *skip*, because they are not working at the moment. The new *tox* environment is added to the Travis-CI configuration to run the tests on Travis and upload the coverage to codecov.
Adds a simple test for the `banned_ports_to_str` method in `shell_manager.config` and a simple test for the `sanitize_name` method in `shell_manager.util` (to trigger the Travis job).
Adds badges for the build and the coverage to `README.md`
Related issues: #276 and #277

Add Travis-CI configuration to run picoCTF-shell tests

---

.gitignore
ansible/roles/common/defaults/main.yml
vagrant/provision_scripts/install_ansible.sh

Resolves breaking issue with recently released Ansible 2.8:
```
TASK [pico-web : Synchronize picoCTF-web to a directory on host] ***************
fatal: [dev_web]: FAILED! => {"changed": false, "cmd": "sshpass -d6 /usr/bin/rsync --delay-updates -F --compress --delete-after --archive '--out-format=<<CHANGED>>%i %n%L' /picoCTF/picoCTF-web/ /picoCTF-web-build", "msg": "[Errno 32] Broken pipe", "rc": 32}`
```

Pin the Ansible version

---

ansible/roles/common/defaults/main.yml
ansible/roles/common/tasks/main.yml
vagrant/provision_scripts/install_ansible.sh

Previously, the version of Ansible pulled from their PPA ran using Python 2.
When switching Ansible to a pinned PyPI version in #300, I also switched Ansible to run using Python 3.
This silently broke authentication between the shell server and wetty.js, so this reverts Ansible to run using Python 2 while still pinning its version to 2.7.

[Bugfix] Run pinned Ansible with Python 2.7

---

picoCTF-web/api/apps/v1/minigames.py

Fixes a bug where the minigame secret could not be found and requests would fail as 500s.

[Bugfix] v1 minigame submission endpoint

---

picoCTF-web/web/coffee/front-page.coffee

- Hide firstname and lastname fields by default
- Show gender demographic field by default
- Always prompt for school/organization URL (previously only displayed to students)
- Slightly reorganize registration form
- Move Country/Region of Residence into its own row above school/demographics section
- Place school/organization name and URL into the same row
- Grade (for students) / subjects taught (for teachers) occupy the same row

Update registration fields

---

picoCTF-web/api/apps/v1/groups.py
picoCTF-web/api/apps/v1/schemas.py
picoCTF-web/api/apps/v1/users.py
picoCTF-web/api/group.py
picoCTF-web/setup.py
picoCTF-web/web/coffee/classroom-management.coffee
picoCTF-web/web/coffee/front-page.coffee
picoCTF-web/web/files/picoctf_batch_import.csv

Adds a module to the classroom management view allowing teachers to batch-register students by uploading a CSV.
Batch-registered accounts:
- Require only Age, Grade, and (optionally) Gender fields to be filled out
- Email, parent email, country of residence, and school name/country/ZIP code/URL are pulled from the initiating teacher account and group
- Bypass email verification and reCAPTCHA, if enabled
- Have usernames of the form `<teacher_username>.<student_n>`. Since `.` is typically disallowed for usernames, these accounts are guaranteed to be available
- Have automatically generated passwords, which are displayed once at registration time or can otherwise be changed through password reset
- Are automatically added to the classroom from which they were added
The underlying API call …

Add student batch registration

---

ansible/roles/pico-shell/tasks/main.yml
picoCTF-web/api/apps/v1/user.py
picoCTF-web/api/team.py
picoCTF-web/api/user.py
picoCTF-web/web/account.html
picoCTF-web/web/coffee/account.coffee

Disable account was updated to delete account where only the uid, username, password_hash and tid are saved while all other user details are made as null.
Closes #267

Delete Account and hidepid

---

picoCTF-web/api/apps/v1/teams.py
picoCTF-web/api/apps/v1/user.py
picoCTF-web/api/apps/v1/users.py
picoCTF-web/api/team.py
picoCTF-web/api/user.py

Resolves #316 
- Team eligibility is calculated based on non-disabled members only
- To prevent an ineligible member from helping a team and then self-disabling, ineligibility is now "sticky". However, a team formerly known to be eligible is still checked every time
- Added `/teams/<tid>/recalculate_eligibility`, where an admin can force a re-evaluation of a team's eligibility in the case of honest mistakes
- Added `DELETE /user/<uid>`, allowing an admin to directly disable an account. Previously, a user could only self-disable their account with password confirmation using `POST /user/disable_account`
- Teams' countries are recalculated when a member leaves (is disabled). If this causes a formerly 
mixed-country team to become homogenous again, its country will update from `??` to e.g. …

Update team eligibility behavior re: disabled accounts

---

ansible/roles/pico-shell/tasks/dependencies.yml
ansible/roles/pico-shell/templates/shell.nginx.j2
ansible/roles/pico-web/tasks/dependencies.yml
ansible/roles/pico-web/templates/ctf.nginx.j2

Prevents `Server: nginx/$VERSION (Ubuntu)` from being returned in HTTP responses, as noted by @archituiet

Suppress the Server header in responses

---

picoCTF-web/api/apps/v1/groups.py
picoCTF-web/api/apps/v1/schemas.py
picoCTF-web/api/apps/v1/teams.py
picoCTF-web/tests/api/functional/v1/test_teams.py

Limit the acceptable characters when creating teams and classrooms to prevent abuse.
resolves #335

Sanitize team and classroom names

---

ansible/roles/pico-shell/tasks/deploy_problems.yml

Newer ansible expects octal or string representations.
Fixes broken launch of web problems and who knows what else
Resolves #341

Fix permissions setting of /tmp breaking uwsgi

---

ansible/roles/pico-shell/tasks/deploy_problems.yml

Followup, update format in c391fb7 to be consistent
`/etc/xinet.d` was incorrect assigned as well

Standardize octal format of ansible perm setting

---

Vagrantfile
ansible/roles/pico-web/templates/ctf-daemon.service.j2
ansible/roles/pico-web/templates/gunicorn.service.j2

Note: does not appear to be possible to address the vagrant mount order
issue with systemd dependencies, as sync occurs sometime after
systemd units are all loaded.
Resolves #260

Remove service start delay on web, use vagrant to restart services

---

picoCTF-web/api/apps/v1/team.py
picoCTF-web/api/apps/v1/user.py
picoCTF-web/api/team.py
picoCTF-web/tests/api/functional/v1/test_team.py
picoCTF-web/tests/api/functional/v1/test_user.py

Leaves some extra team data internally for group-related calls.
Removes most of problem data even for admins, as that is otherwise available from
problem routes.

Trim data from user and team endpoints extraneous to front-end

---

picoCTF-web/api/apps/v1/schemas.py
picoCTF-web/web/jsx/management-settings.jsx

Currently GET outputs RFC822-formatted time while PATCH expects ISO8601-formatted time. This makes both of them use RFC822.
Fixes #361

Making GET and PATCH /v1/settings use the same time format

---

picoCTF-web/api/apps/v1/groups.py
picoCTF-web/api/apps/v1/schemas.py
picoCTF-web/api/apps/v1/team.py
picoCTF-web/api/group.py
picoCTF-web/api/stats.py
picoCTF-web/api/user.py
picoCTF-web/tests/api/functional/v1/test_team.py
picoCTF-web/web/classroom.html
picoCTF-web/web/jsx/classroom-management.jsx
picoCTF-web/web/jsx/classroom.jsx
picoCTF-web/web/jsx/scoreboard.jsx

All users join groups (classrooms) in student roles, and can only be promoted to the teacher role by someone who already holds that role within the group or an administrator.
Slightly reworks the classroom management view, separating teachers into their own list.
Resolves #386

Require manual teacher role elevation in classrooms

---

picoCTF-web/api/apps/v1/team.py
picoCTF-web/api/apps/v1/teams.py
picoCTF-web/api/user.py
picoCTF-web/tests/integration/test_team.py

- Raise exception on join/create when team_name == username
- Create self-teams with invalid (too short) password that are valid utf-encoded

Fix uncaught exception when user tries to create/join self-team

---

ansible/roles/pico-shell/templates/shell.nginx.j2
ansible/roles/pico-web/files/nginx.conf
ansible/roles/pico-web/files/override.conf
ansible/roles/pico-web/tasks/nginx.yml
ansible/roles/pico-web/templates/ctf.nginx.j2
ansible/roles/pico-web/templates/gunicorn.service.j2

- Increase worker nofile to 65535, connections to twice the 768 default
- server_tokens off instead of removing Server header
- Add reuseport for nginx 443 listener
- Cache static files on web server for 60s
- Config systemd for LimitNOFILE for nginx and gunicorn
- Decrease proxy header buffer size from 4k to 2k
- Increase proxy_buffers from 8 to 24 based on largest pico2019 non-admin request payload of 80KB from `/problems`

Tune nginx config

---

picoCTF-web/api/apps/v1/schemas.py

This fixes a bug some users have been reporting where the reset password page only accepts a max 20-char length password and throws a misleading error message.

Make max password lengths consistent

---

picoCTF-web/api/apps/v1/problems.py
picoCTF-web/api/problem.py
picoCTF-web/api/problem_feedback.py
picoCTF-web/api/submissions.py

- Reduces get_solved_problems memoized value by orders of magnitude
- Resolves #405
- Likely reduces memory bloat of worker threads doing problem/score
related operations

Reduce the payload of problems.find() queries with optional filter

---

picoCTF-web/api/apps/v1/groups.py
picoCTF-web/api/db.py
picoCTF-web/api/stats.py
picoCTF-web/api/submissions.py
picoCTF-web/api/team.py
picoCTF-web/daemons/cache_stats.py

Checks submissions for suspiciousness (are they incorrect, but have the correct flag for another team's instance?) at submission time and stores this as a property of the submission.
Removes the need for a recurring check across all submissions. After all, a submission can only be considered suspicious based on the instances that exist at the time of that submission.
Removes the `groups/<gid>/flag_sharing` call, which was not used by the frontend.

Refactor suspicious submissions

---

picoCTF-shell/hacksport/deploy.py
picoCTF-shell/hacksport/install.py
picoCTF-shell/shell_manager/run.py

- Hopefully fixes instance undeployment by killing processes associated with an instance port before attempting to remove instance users, and skipping steps that error
- Allows for problem reinstallation with `--reinstall` flag, which avoids having the problem wiped from the port map via `uninstall`. Instances need to be un- and re- deployed after reinstallation to use the updated source files.

Shell manager undeployment/update changes

---

picoCTF-web/api/problem.py
picoCTF-web/api/stats.py

Allowing for future functionality where a user can solve a previous
team solve for own learning, but team score weighting only applies to
first solve of a pid.
Reduces need for two db.submissions queries, earliest solve time is now
returned from api.problem.get_solved_problems

Fix misweighted scoreboard listing when a user re-solves team solve

---

picoCTF-web/api/apps/v1/groups.py
picoCTF-web/api/apps/v1/team.py
picoCTF-web/api/apps/v1/teams.py
picoCTF-web/api/apps/v1/users.py

Strips beginning and trailing whitespace from team names, group names, batch registration fields, and user affiliations.
Resolves #417 
Resolves #427 
Not backportable into 2019 deployment due to existing team/group names with trailing spaces (these teams/groups would become unjoinable)

Trim whitespace on various fields

---

picoCTF-web/api/apps/v1/team.py
picoCTF-web/api/apps/v1/user.py
picoCTF-web/api/team.py
picoCTF-web/api/user.py
picoCTF-web/web/jsx/profile.jsx

Allows team members to leave / be kicked as long as they haven't submitted any flags.
* Users who are kicked or elect to leave a team are placed back on their self-team, bringing along any group memberships they obtained along the way.
* Only team creators can kick other members
* Anyone can leave, team creators can only leave if they are the only remaining member
* The team creator is labeled as the captain in the member list
* If a custom (non-self) team hits 0 members, it is removed
Resolves #432

Conditional removal of team members

---

picoCTF-web/api/email.py

Resolves #436 (It seemed more likely that a parent would recognize their child's email than their username at a glance.)
Should be cherry-pickable into release-2019 / 2019 private

Add student's email address to parent verification email subject

---

picoCTF-web/api/__init__.py

Reference: https://werkzeug.palletsprojects.com/en/0.16.x/contrib/fixers/
Deprecated since version 0.15: ProxyFix has moved to
werkzeug.middleware.proxy_fix. All other code in this module is
deprecated and will be removed in version 1.0.
Caused by transitive dependency update of Werkzeug to 1.0.0

Update to import for ProxyFix due to deprecation

---

picoCTF-web/setup.py

Should be temporary. Should also consider transition to flask_restx as
flask_restplus is currently unmaintained.
reference:
https://github.com/noirbizarre/flask-restplus/issues/777
https://github.com/python-restx/flask-restx/pull/39
https://github.com/python-restx/flask-restx/issues/34
notice from flask_restplus: https://github.com/noirbizarre/flask-restplus#flask-restplus
"This project has been forked to Flask-RESTX and will be maintained by
by the python-restx organization. Flask-RESTPlus should be considered
unmaintained."

Pin werkzeug dependency due to dependency requirements

---

ansible/roles/pico-web/templates/ctf.nginx.j2

An update to the webserver nginx config to prevent bypassing the `auth_request` function by `.html` to the end of your URL (for example, you can briefly see the management page when unauthenticated by visiting https://2019game.picoctf.com/management.html but cannot if you visit https://2019game.picoctf.com/management ). Currently, there is no immediate security issue with the old config since `redirectIfNotAdmin()` kicks in prior to the API loading the important data, but this could be an issue in the future (and is easy to fix).

Update to web nginx config to prevent visiting restricted pages

---

picoCTF-web/api/user.py

**Issue:**
The `picoCTF` web interface has a configuration box for blacklisted
usernames and a function that checks a username against that list.
However, the check function was not called during the user creation
process.  This lack of checking allows registrations with `root`
and `hacksports` to occur.
**Note:**
This bug is not a catastophic vulnerability because the current
configuration of PAM forces local authentication for local users.
It currently results in these users being unable to log into the
shell server because their password is checked against the shadow
file and not the user database.
**Changes:**
- Renames the blacklist check function to make its semantics clear.
- Adds the check to `add_user` and returns the "There is already a
user with this username" message when in …

Check 'blacklist' when creating users

---

picoCTF-web/api/user.py

**Issue:**
The regex used for comparing registration emails to a provided
whitelist is vulnerable to a stuffing attack when paired with the
verification email process.  Specifically, an attacker can enter
an email in the form `bad@bad.com;good@good.com` which will pass
a domain check for `good.com` but send the verification email to
`bad@bad.com`.
**Note:**
The modified regex now forces the entire portion after the first
`@` to match the admin provided regex.  This is not strictly RFC
compliant (`@` symbol is allowed in quoted local part), but is
effective and should not cause issues for non-ASCII character sets
either.
**Changes:**
- Modify regex for local part to always terminate at the `@` symbol.

Close bypass method for email whitelists

---

ansible/roles/pico-shell/tasks/nginx.yml
ansible/roles/pico-shell/tasks/permissions.yml

Any participate can currently directory list `/usr/share/nginx/html/static/` and see every static file for every problem (including instances not assigned to them) with `ls -Rla /usr/share/nginx/html/static/` or a similar command.  This update simply removes the ability to directory list `/static/` (similar to how directory listing is removed from `/problems`) simply by changing the permission from **755** to **751**. The update seeks to create the initial `/usr/share/nginx/html/static/` with updated permissions as well as to update the permissions of the file if it is already created. I have not fully tested all features after changing the permissions but it does not impact downloading of static files (i.e. you can still download files that are linked, and I have not found anything else …

update shell folder permissions so can not directory list /html/static

---

Vagrantfile
infra_local/README.md
scripts/vagrant-env.sh

@carlislemc , fix for #470 
Symptom in the issue was an incorrect configuration causing the example DockerChallenge deployment to fail. In the configuration the docker host is inferred from the shell `ansible_host` setting.
Root cause was that the use of `{{ lookup('env','SIP') or '192.168.2.3' }}` was failing when run with the `ansible_local` provisioner (as used by the Vagrantfile). The lookup is performed on the controller (in this case the vm itself).
This fix adds an additional provisioning script to properly set SIP/WIP in the vms.
Tested a fresh build with the command:
```
J=4 M=8 WIP=192.168.2.52 SIP=192.168.2.53 vagrant up --provision shell && J=2 M=8 WIP=192.168.2.52 SIP=192.168.2.53 vagrant up --provision web
```
As well as a fresh build with just a plain default:
```
vagrant …
```

Fix vagrant ENV SIP/WIP regression

---

Vagrantfile

Fixes issue when starting platform via Virtualbox on Windows (without WSL), as otherwise synced folder is given 777 permissions and Ansible refuses to read `infra_local/ansible.cfg`.
```
[WARNING] Ansible is being run in a world writable directory (/picoCTF/infra_local), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
ERROR! the role 'common' was not found in /picoCTF/infra_local/roles:/home/vagrant/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/picoCTF/infra_local
The error appears to be in '/picoCTF/infra_local/site.yml': line 12, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
roles:
- {role: …
```

Fix Ansible permissions issue with Windows synced directory

---

Vagrantfile

Pins the Ansible version to 2.9.11 to avoid a breaking change to the default file
mode in 2.9.12 (https://github.com/ansible/ansible/issues/71200)
Resolves #475

Pin Ansible version

---

picoCTF-shell/hacksport/problem_templates.py

Most protections are disabled by default, but disabling PIE requires adding an extra flag in the compiler options.

Updated CompiledBinary example to automatically disable PIE

---

ansible/pico-shell/defaults/main.yml
ansible/pico-shell/files/pam_auth.py
ansible/pico-shell/templates/wetty.service.j2

Fixes issues preventing SSH login to the shell server and successful wetty server startup.
- Resolves #478 by adding missing dist-packages directories to libpam-python import path
- Updates wetty.js location and launch flags to match current version

Shell login fixes

---

Vagrantfile
ansible/common/tasks/utils.yml
infra_local/README.md
infra_local/inventory.yml
infra_remote/inventory.yml

During internal use of PICO for teaching purposes, two
issues often popped up:
1. Something kept breaking down (auth for example), due to
background updates
2. Students often used vs-code servers, which in a class of 90,
ate up the 10GB default disk space
These changes implement:
- "SHELL_DISK_SIZE": An environment variable with value of the form
`XGB` with X being a numberic value, to control max disk size.
- "disable-unattended-upgrades": A Flag in the anisble config to
uninstall `unattended-upgrades`, preventing unwanted updates on
private deployments.
I tested the deployment on Windows 10 deployment, backed with VirtualBox.
In order to try out the disk resize utility, Try
1. `bash`: `SHELL_DISK_SIZE=20GB vagrant up`
2. `powershell`:  `$env:SHELL_DISK_SIZE = "20GB"; vagrant up`
The …

Add flags to control Disk_Size & unattended-up

---

Vagrantfile

As of 23rd January, 2021, pip v21.0 depricated python2
and removed support for python2. As of now, ansible seems to use
python2 for deployment.
https://github.com/pypa/pip/issues/6148
This broke the installation. For hotfix, added custom pip install
command based on Vagrant's ansible local documentation
https://www.vagrantup.com/docs/provisioning/ansible_local
```bash
vagrant up
```
Note: Requires fairly recent version of vagrant

Hotfix: Ansible install, python2 depricated

---

picoCTF-shell/setup.py

`idna` recently released version 3.  This causes a version conflict in the `picoCTF-shell` during install because `urllib3` is installed before `requests`.  `urllib3` does not specify an upper bound on `idna`'s version, but `requests` does (`idna<3`).  Since `idna 3.1` is already installed by the time pip attempts to resolve `requests`, the process fails.

Force idna package version
