ansible/README.md, ansible/group_vars/common.yml, ansible/group_vars/staging.yml, ansible/host_vars/staging_db.yml, ansible/host_vars/staging_shell.yml, ansible/host_vars/staging_web.yml
This updates the Readme and common variables to match the current state of the project and better explain the role of Ansible in deploying and configuring picoCTF.
=> Update Ansible Documentation

ansible/inventories/devploy, ansible/inventories/local_development, ansible/inventories/local_testing, ansible/inventories/remote_testing, ansible/roles/common/tasks/main.yml, ansible/roles/common/tasks/set_hostname.yml
- updates the hostname based on the inventory
- updates /etc/hosts as well
=> Added hostname setting

vagrant/README.md, vagrant/jump_box/Vagrantfile, vagrant/provision_scripts/install_ansible.sh, vagrant/provision_scripts/install_terraform.sh
This pull request expands the provisioning of the "jump box" to include the Terraform tool.
=> Add Terraform to jump box

ansible/roles/pico-shell/tasks/deploy_problems.yml
I have tested this on my MacBook Pro, using VirtualBox 5.1.26.
=> Fix missing quotes in deploy_problems.yml

Vagrantfile
Should fix [issue #53](https://github.com/picoCTF/picoCTF/issues/53). Tested on personal Windows 10 machine via Cygwin.
=> Modified Vagrantfile to fix permission errors on Windows.

picoCTF-web/setup.py
=> Pin Flask < 1.0

Vagrantfile
We can move to rubocop later if it is more suitable. For now, rufo seems
to do the job for this lone file.
=> Format Vagrantfile with rufo before introducing changes

README.md
This change is write-space only and is a preparation for upcoming content changes.
=> Format README.md before content change

picoCTF-shell/hacksport/deploy.py
Fix for issues #103 
Ever time a new instance was created, xinetd was restarted. This has been changed to only restart xinetd once all of the instances have finished being created. 
Verified the crash no longer occurs.
=> Mutli instance fix

ansible/roles/pico-shell/tasks/dependencies.yml, ansible/roles/pico-shell/tasks/shell_manager.yml
- Pin python `requests`, upgrade `cryptography` per dependency warning msg
- Add symlink to virtualenv'd `shell_manager` from `/usr/local/bin`
=> Add minor QoL changes to xenial upgrade

problems/examples/cryptography/ecb1/ecb.py, problems/examples/cryptography/ecb1/problem.json
`pycrypto` not included by default, install via problem `pip_requirements`
=> Update ecb.py sample problem to python3

ansible/roles/pico-shell/templates/config.json.j2, picoCTF-shell/hacksport/deploy.py, picoCTF-shell/shell_manager/util.py
- Changed default port usage to be 1025-65535.
- Added check to insure port is not already in use by a system process or other pico problem.
- Cleaned up code.
fixes #18
=> Fixed diplucate port issue

picoCTF-web/api/problem.py, picoCTF-web/api/routes/problem.py
Removes unnccessary and revealing problem data in `api/problem` GET routes,
addressing #43 flag leaks.
`api/problem/:pid` does still return full instance (and flag) data for admins.
Comparison:
<details><summary>Old api/problems/</summary>
```
{
"status": 1,
"message": null,
"data": [
{
"name": "SQL Injection 1",
"category": "Web Exploitation",
"pkg_dependencies": [
"php7.0-sqlite3"
],
"description": "There is a website running at http://192.168.2.3:10987. Try to see if you can login!",
"score": 40,
"hints": [],
"author": "Tim Becker",
"organization": "ForAllSecure",
"sanitized_name": "sql-injection-1",
"disabled": false,
"pid": "4508167aa0b219fd9d131551d10aa58e",
"solves": 0,
"user": "sql-injection-1_1",
"deployment_directory": "/problems/sql-injection-1_1",
"service": …
```
=> Sanitize `api/problems` return data

picoCTF-shell/hacksport/status.py
=> Added Null check to fix status command

ansible/roles/pico-web/templates/ctf.nginx.j2
Minor adjustment to #138 to enable password resetting
Resolves #131
=> Fix auth restriction on pw reset page

picoCTF-web/api/team.py
Cache was not invalidated for list of solved problems for both joining
player and team after `join_team` event, now forces refresh.
Original issue reproduction:
1. Create account and `team1` as `leader1`.
2. Create account as `player2` without joining team.
3. Solve `problem-A` as `player2`
4. Join `team1` as `player2`.
At this point, all members of `team1` do not see `problem-A` as solved. This
would not be resolved until a new correct flag is able to be submitted (past
cached problem-locked and already-solved limitations).
=> Fix solved problems not updating on team join

picoCTF-web/web/classroom.html, picoCTF-web/web/coffee/progression_graphs.coffee
Addresses team scoreboard, global scoreboard, and classroom scoreboard
=> Fix charting for Chart.js 2.0+ changes

picoCTF-web/api/logger.py, picoCTF-web/api/problem.py, picoCTF-web/api/routes/problem.py, picoCTF-web/web/coffee/problems.coffee
=> Add flag submission source field `method`

picoCTF-web/web/coffee/management-problems-graphs.coffee, picoCTF-web/web/coffee/management-problems.coffee
Per chart.js 2.0 config for doughnut chart.
Resolves #157
=> Update problem management chart.js config

ansible/roles/pico-web/defaults/main.yml, ansible/roles/pico-web/tasks/picoCTF-webapp.yml
=> Copy web dir to a dir on host before jekyll build

picoCTF-web/web/shell.html
=> Improve shell tab instruction to explain copy and paste

ansible/roles/pico-shell/defaults/main.yml, ansible/roles/pico-shell/tasks/dependencies.yml, problems/bundles/challenge-sampler-tools.json
We migrate from using an empty problem bundle to using Ansible.
Resolves #185
=> Take control of tools we install on shell server

picoCTF-web/api/routes/stats.py, picoCTF-web/api/stats.py, picoCTF-web/daemons/cache_stats.py, picoCTF-web/web/coffee/front-page.coffee
=> Registration stats

.editorconfig
I am submitting this PR for discussion. We can certainly change the content (but whatever was in 2018 felt wrong, as explained in the commit message).
=> Update .editorconfig to reflect my understanding in 2019

picoCTF-web/api/routes/user.py, picoCTF-web/api/user.py
If a previous nonce is newer than the supplied nonce value, update is rejected.
=> Add optional nonce check to extdata payload

picoCTF-shell/shell_manager/util.py, picoCTF-web/api/config.py, picoCTF-web/api/problem.py, picoCTF-web/api/routes/problem.py, picoCTF-web/api/routes/user.py, picoCTF-web/api/user.py, problems/examples/binary-exploitation/buffer-overflow-1/problem.json, problems/examples/cryptography/ecb1/problem.json
Walkthroughs additional text field of a problem
Tokens are earned through completing minigames, based on mapped values
Tokens can be used to unlock walkthroughs for problems
The exact naming of the api endpoints is definitely flexible
=> Add walkthroughs and tokens

ansible/roles/pico-shell/files/pam_auth.py
=> Clarify password prompt

.gitignore, ansible/roles/common/defaults/main.yml, ansible/roles/common/tasks/main.yml, vagrant/provision_scripts/install_ansible.sh
Ports #300 and #301 to the 2018 branch, fixing a blocking bug with Ansible at VM startup.
=> Port Ansible fix to 2018 release branch

ansible/roles/pico-shell/defaults/main.yml, ansible/roles/pico-shell/files/ssl-pico.chained.crt, ansible/roles/pico-shell/tasks/nginx.yml, ansible/roles/pico-shell/templates/shell.nginx.j2, ansible/roles/pico-web/defaults/main.yml, ansible/roles/pico-web/files/ssl-pico.chained.crt, ansible/roles/pico-web/tasks/nginx.yml, ansible/roles/pico-web/templates/ctf.nginx.j2
ssl-pico.key.vault_encrypted should obviously be encrypted by ansible vault
=> Add SSL cert install to shell and web

picoCTF-web/api/__init__.py, picoCTF-web/api/config.py, picoCTF-web/web/coffee/management-settings.coffee
- Adds settings to general config tab:
- parent verification email
- max verification emails 
- username blacklist
- max team size
- (didn't include achievements settings since that feature is not enabled/working currently)
- New admin config tab for CAPTCHA settings
- New admin config tab for eligibility settings
- Adds any new default_settings keys to the database settings on app startup
closes #199, closes #213
=> Runtime settings updates

ansible/roles/mongodb/tasks/configure_auth.yml, picoCTF-shell/setup.py, picoCTF-web/setup.py
Note: python-pymongo ubuntu package is outdated at this time
=> Install pymongo via pip and update python packages

picoCTF-shell/hacksport/deploy.py
=> Fix deploying problems from source

picoCTF-shell/hacksport/deploy.py, picoCTF-shell/shell_manager/package.py
I was just kidding in #330 
resolves #327
=> Actually fix problem source deployments

picoCTF-web/api/apps/v1/user.py, picoCTF-web/api/apps/v1/users.py, picoCTF-web/web/account.html, picoCTF-web/web/coffee/account.coffee
Adding user and admin api endpoints that export all data associated with a user.
(resolves #311 )
=> Exporting user data

picoCTF-web/api/apps/v1/schemas.py, picoCTF-web/api/reqparse.py, picoCTF-web/tests/api/functional/v1/test_user.py
Forked reqparse to add a custom error field to be displayed in the browser.
resolves #328
=> Better validation error message

picoCTF-web/api/config.py, picoCTF-web/api/email.py, picoCTF-web/tests/api/functional/v1/test_user.py
Unhardcoded emails in email.py, and moved them into settings["email"] so that they can be patched
resolves #42
=> Unhardcode emails

picoCTF-web/api/config.py, picoCTF-web/api/email.py
=> Add username to verification email

Vagrantfile, ansible/roles/pico-web/templates/ctf-stats.timer.j2
Per changes in a111c342 of ctf-stats over ctf-daemon
=> Delay boot ctf-stats, disable ctf-daemon restart

picoCTF-web/api/stats.py
Last-submission time searches now by active member uids individually,
properly weighting times that may be prior to joining the current team
Resolves #349
=> Default time-weighting of last correct submission to now() if not found

picoCTF-web/api/apps/v1/schemas.py, picoCTF-web/api/apps/v1/users.py, picoCTF-web/api/user.py, picoCTF-web/web/jsx/management-settings.jsx
Adding an interface for user management.
closes #312 & closes #253
=> Search and delete

picoCTF-shell/hacksport/deploy.py, picoCTF-shell/shell_manager/util.py, picoCTF-web/api/problem.py, picoCTF-web/web/jsx/management-problems.jsx
Add boolean param to problem.json
=> Generate max 1 instance for a 'static_flag' problem

ansible/roles/pico-shell/tasks/main.yml
=> Remove /var/log/wtmp on provision

ansible/roles/pico-shell/files/sshd_config, ansible/roles/pico-shell/files/sshkey_auth.py, ansible/roles/pico-shell/tasks/pam_and_services.yml
=> Checks for valid user before accepting ssh auth key

ansible/roles/pico-shell/files/limits.conf, ansible/roles/pico-shell/files/pam_auth.py, ansible/roles/pico-shell/files/pam_session.py, ansible/roles/pico-shell/files/sshd_config, ansible/roles/pico-shell/templates/tc-limit.service.j2
=> Userlogin conf

picoCTF-web/api/apps/v1/groups.py, picoCTF-web/api/apps/v1/users.py, picoCTF-web/web/jsx/front-page.jsx
`['Male', 'Female', 'Non-Binary/Gender-Fluid', 'Not Listed/Prefer not
to answer']` maps to `['male', 'female', 'nb/gf', 'nl/no']`
=> Update registration demo data

picoCTF-web/api/apps/v1/team.py, picoCTF-web/api/email.py, picoCTF-web/api/team.py, picoCTF-web/api/user.py, picoCTF-web/tests/integration/test_team.py, picoCTF-web/tests/integration/test_users.py
- Drops empty teams from groups
- Remove unused team['country'] param and tracking
- Invalidate cache entries
=> Update user account process

ansible/roles/pico-web/files/start_competition.py, picoCTF-web/api/config.py, picoCTF-web/api/db.py, picoCTF-web/api/stats.py, picoCTF-web/api/team.py, picoCTF-web/api/user.py, picoCTF-web/daemons/cache_stats.py
TODO Profiling:
- problems
- submissions
=> WIP: Update mongodb indexes based on utilized queries

ansible/roles/mongodb/templates/redis.conf.j2, picoCTF-web/api/problem.py, picoCTF-web/api/stats.py, picoCTF-web/api/team.py
Address redis OOM issues found in load-testing
=> Redis tuning

picoCTF-web/api/apps/v1/team.py, picoCTF-web/api/team.py, picoCTF-web/tests/integration/test_team.py
Restore `country` of **user** as team['members']
Previously:
```
**Members** (2/5):
- student1 (Other -)
- student2 (Other -)
```
Fixed:
```
**Members** (2/5):
- student1 (Other - US)
- student2 (Other - CA)
```
=> Partial reversion of b8bf2240, fix profile user country listing

picoCTF-web/api/apps/v1/minigames.py, picoCTF-web/api/group.py, picoCTF-web/api/problem.py
They all should be unique anyhow
Fix existing entries
```
import api
with api.create_app().app_context():
db = api.db.get_conn()
all_groups = list(db.groups.find())
for group in all_groups:
u_members = list(set(group['members']))
u_teachers = list(set(group['teachers']))
db.groups.update_many({'gid': group['gid']}, { '$set' : {
"members": u_members,
"teachers": u_teachers
}})
```
=> Change all mongo array $push to $addToSet

picoCTF-web/api/cache.py
Does not remove cached value first, resulting in gap of value return, but instead replaces value only when returned from the actual function call
This should address several of our worst woes in load testing, which I believe came from gaps during the ctf-stats service first invalidating a cache, then taking 5 minutes to recache the result of the expensive function call and. During this time, every worker hitting that endpoint would be likewise performing same (5-minute) action.
=> Significantly improve memoization called with reset_cache

picoCTF-web/api/apps/v1/problems.py, picoCTF-web/api/problem.py, picoCTF-web/api/problem_feedback.py, picoCTF-web/web/jsx/management-problems.jsx
Additional filter/projections of database queries to reduce unnecessary bulk in requests and memory
=> WIP: Slim queries

picoCTF-shell/hacksport/deploy.py
=> Truncate problem instance username to 28chars

ansible/roles/pico-shell/files/limits.conf, ansible/roles/pico-web/tasks/nodejs.yml, picoCTF-web/api/config.py, picoCTF-web/web/classroom.html, picoCTF-web/web/jsx/classroom.jsx
- Resolves #452
- Resolves #453 
- Addresses peripheral issue of EOL warning for nodejs 8 per #458
=> Maintenance update

ansible/roles/pico-web/files/add_shell_server.py
resolves #463 by updating the usage to match the current web api
=> Fix auto load with add_shell_server.py
